id: jbossdemocentral-bpms-signavio-integration
title: JBoss BPM Suite Signavio Integration Demo
github_repo_url: https://github.com/jbossdemocentral/bpms-signavio-integration-demo
technologies:
  - JBoss EAP
  - JBoss BPM Suite
summary: The example project mortgage demo that is delivered with JBoss BPM Suite, but in this case we are importing the process as designed externally in the Signavio Process Editor and extending it with execution implementation details to run the mortage process. 
level: Intermediate
product: bpmsuite
author: Steven Lawandowski, Babak Mozaffari, Eric D. Schabell
